name: dart_js_example 
description: Simple dart:js_interop example
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  jaspr: ^0.21.7

dev_dependencies:
  lints: ^6.0.0
