name: jaspr_content_mermaid 
description: jaspr_content mermaid support
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  jaspr: ^0.21.7
  jaspr_content: ^0.4.4
  syntax_highlight_lite: ^0.0.1

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.10.4
